<a href="https://colab.research.google.com/github/rijul27/Numpy/blob/main/Advance_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.zeros((5,5))

In [3]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
row = np.array([7,8,9,4,6])

In [5]:
row

array([7, 8, 9, 4, 6])

In [7]:
arr.shape

(5, 5)

In [8]:
row.shape

(5,)

In [9]:
arr + row  # Add as a row-wise (Broadcasting)

array([[7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.]])

In [17]:
column = np.array([[1,3,4,6,2]]) # 2D array beacuse 2 [[]]

In [18]:
column

array([[1, 3, 4, 6, 2]])

In [19]:
column.shape

(1, 5)

In [20]:
column.ndim

2

In [21]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
column.T

array([[1],
       [3],
       [4],
       [6],
       [2]])

In [24]:
column.T + arr # Column-wise Broadcasting

array([[1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2.]])

In [26]:
# Array Manipulation
arr1 = np.random.randint(1,20,(4,5))

In [27]:
arr1

array([[15, 15,  8,  2,  9],
       [ 4,  9,  8, 16,  1],
       [ 9,  4,  7,  2,  9],
       [10,  5,  3, 10, 19]])

In [30]:
arr1.size

20

In [31]:
arr1.shape

(4, 5)

In [32]:
# for reshape size should be same as here is 20
arr1.reshape(10,2)

array([[15, 15],
       [ 8,  2],
       [ 9,  4],
       [ 9,  8],
       [16,  1],
       [ 9,  4],
       [ 7,  2],
       [ 9, 10],
       [ 5,  3],
       [10, 19]])

In [33]:
arr1.reshape(5,4)

array([[15, 15,  8,  2],
       [ 9,  4,  9,  8],
       [16,  1,  9,  4],
       [ 7,  2,  9, 10],
       [ 5,  3, 10, 19]])

In [36]:
s = arr1.flatten() # Matrix to list 2D array -> 1D array

In [37]:
s.shape

(20,)

In [38]:
s

array([15, 15,  8,  2,  9,  4,  9,  8, 16,  1,  9,  4,  7,  2,  9, 10,  5,
        3, 10, 19])

In [39]:
arr2 = np.array([1,2,4,4,5])

In [40]:
arr2

array([1, 2, 4, 4, 5])

In [41]:
arr2.ndim

1

In [47]:
temp1 = np.expand_dims(arr2,axis=1) # expand the dimensions column-wise

In [45]:
temp1

array([[1],
       [2],
       [4],
       [4],
       [5]])

In [46]:
temp1.ndim

2

In [48]:
temp2 = np.expand_dims(arr2,axis=0)

In [49]:
temp2

array([[1, 2, 4, 4, 5]])

In [51]:
temp2.shape

(1, 5)

In [50]:
temp2.ndim

2

In [52]:
matrix = np.array(([2],[5],[6]))

In [53]:
matrix

array([[2],
       [5],
       [6]])

In [54]:
matrix.shape

(3, 1)

In [55]:
matrix.squeeze()

array([2, 5, 6])

In [57]:
sq = np.squeeze(matrix)

In [58]:
sq.shape

(3,)

In [59]:
arr2

array([1, 2, 4, 4, 5])

In [60]:
np.repeat(arr2,3)

array([1, 1, 1, 2, 2, 2, 4, 4, 4, 4, 4, 4, 5, 5, 5])

In [61]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.diagonal(arr)

array([0., 0., 0., 0., 0.])

In [65]:
arr3 = np.array([1,5,6,7,8])

In [66]:
np.diag(arr3)

array([[1, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 8]])

In [67]:
# Binary Operation

arr1 = np.random.randint(1,10,(4,3))
arr2 = np.random.randint(1,10,(4,3))

In [68]:
arr1

array([[3, 3, 6],
       [6, 5, 1],
       [7, 5, 7],
       [3, 5, 4]])

In [69]:
arr2

array([[8, 4, 2],
       [4, 5, 5],
       [5, 4, 2],
       [3, 6, 1]])

In [71]:
arr1 & arr2

array([[0, 0, 2],
       [4, 5, 1],
       [5, 4, 2],
       [3, 4, 0]])

In [72]:
arr1 | arr2

array([[11,  7,  6],
       [ 6,  5,  5],
       [ 7,  5,  7],
       [ 3,  7,  5]])

In [74]:
~arr2

array([[-9, -5, -3],
       [-5, -6, -6],
       [-6, -5, -3],
       [-4, -7, -2]])